<template>
<div id="intro">
  <h1 id="into">Welcome</h1>
</div>

  <div class="home">
    <div id="wordz">
 <h1 id="one">I am</h1>
 <h1 id="two">Abdul-Malik</h1>
  <h1 id="four"> A Full Stack </h1>
 <h1 id="five">Web Developer</h1>
   <router-link  to="/about">Let's Go</router-link>
    </div>


<img id="me" src="../assets/people/me.png" alt="me">
  </div>
</template>

<script>
// @ is an alias to /src

import Navbar from '@/components/Navbar.vue';

export default {

  components: {
    Navbar
  }
}
</script>
<style  scoped>
.home{
background-color: #3c096c;
height: 95vh;
}
a{
  position: fixed;
  top:150px;
  right: 500px;
  text-decoration: none;
  border: 2px solid black;
  background-color: white;
  color: #ff7900;
  border-radius: 25px;
  padding: 10px;
  opacity: 0;

    animation: showing 0s ease-in 4s forwards;
    animation-name: slide-in-top;
  animation-iteration-count: 1;
  animation-duration: 2s;
  animation-delay: 4s;
}
#divvie{
  display: inline-block;
}
#into{
  margin-top:20%;
}
#one{
  color: white;
  animation-name: slide-in-left;
  animation-iteration-count: 1;
  animation-duration: 1s;
  animation-delay: 1s;
}
#two{
  color: #ff7900;
  animation-name: slide-in-left;
  animation-iteration-count: 1;
  animation-duration: 2s;
  animation-delay: 1s;
}
#four{
  color: white;
    animation-name: slide-in-left;
  animation-iteration-count: 1;
  animation-duration: 3s;
   animation-delay: 1s;
}
#five{
  color: #ff7900;
  animation-name: slide-in-left;
  animation-iteration-count: 1;
  animation-duration: 4s;
   animation-delay: 1s;
}

#wordz{
  padding-top:5%;
  padding-left: 20px;
  text-align: start;
}
h1{
  
  color:white;
  font-size: 100px;

}
#me{
  position: fixed;
  right: 0;
  bottom: 0;
}
#intro {
  background-color: #5a189a;
  height: 100vh;
  width: 100vw;
  position: fixed;
  z-index: 23379687384;
  top: 0;
  left: 0;
    animation: hide 1s linear 1s 1 forwards;
}

/* animation */
@keyframes hide {
    to {
    z-index: -444;
        opacity: 0;
    }
}
@keyframes showing{
  to{
    opacity: 1;
  }
}

@keyframes myAnim {
  0% {
    background-position: 0% 50%;
  }

  100% {
    background-position: 100% 50%;
  }
}
.slide-in-left {
	-webkit-animation: slide-in-left 2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: slide-in-left 2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

@-webkit-keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}

.slide-in-top {
	-webkit-animation: slide-in-top 2s cubic-bezier(0.250, 0.460, 0.450, 0.940) 3s both;
	        animation: slide-in-top 2s cubic-bezier(0.250, 0.460, 0.450, 0.940) 3s both;
}
/* ----------------------------------------------
 * Generated by Animista on 2022-1-28 9:44:22
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-top
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-top {
  0% {
    -webkit-transform: translateY(-1000px);
            transform: translateY(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}
@keyframes slide-in-top {
  0% {
    -webkit-transform: translateY(-1000px);
            transform: translateY(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}

</style>