<template>


  <div class="home">
  
    <div id="wordz">
 <h1 id="one" class="animate__animated animate__lightSpeedInLeft  animate__delay-0.5s">I am a</h1>
 <h1 id="two" class="animate__animated animate__rollIn  animate__delay-1s">Full Stack</h1>
  <h1 id="four" class="animate__animated animate__flipInX  animate__delay-2s"> Web Developer </h1>
   <router-link class="buttunz animate__animated animate__jackInTheBox animate__delay-4s" to="/about">Let's Go</router-link>
    </div>


<img id="me" src='../assets/people/me.png' alt="me">
  </div>
</template>

<script>
// @ is an alias to /src

import Navbar from '@/components/Navbar.vue';

export default {

  components: {
    Navbar
  }
}
</script>
<style  scoped>
.home{
background:linear-gradient(0deg, rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7)), url("../assets/bg.png");
 height: 100vh;
 overflow: hidden;
 margin-top: 0px;
}
a{
  position: fixed;
  top:150px;
  right: 500px;
  text-decoration: none;
  border: 2px solid black;
  background-color: white;
  color: #ff7900;
  border-radius: 25px;
  padding: 10px;


}
#divvie{
  display: inline-block;
}

#one{
  color: white;

}
#two{
  color: #ff7900;

}
#four{
  color: white;

}
#five{
  color: #ff7900;

}

#wordz{
  padding-top:15%;
  padding-left: 20px;
  text-align: start;
}
h1{
  
  color:white;
  font-size: 75px;

}
#me{
  position: fixed;
  right: 0;
  bottom: 0;
  height: 800px;
}



/* media query */
@media only screen and (max-width: 600px) {
  #me{
display: none;

  }
  #intro{
      padding-top:25%;
  }
  .home{
     background:linear-gradient(0deg, rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7)), url("../assets/people/me.png"),#5a189a;
  }
  h1{

    font-size: 50px;
  }
  #wordz{
    padding-top: 25%;
  }
  
}

/* animation */
@keyframes hide {
    to {
    z-index: -444;
        opacity: 0;
    }
}
@keyframes showing{
  to{
    opacity: 1;
  }
}

@keyframes myAnim {
  0% {
    background-position: 0% 50%;
  }

  100% {
    background-position: 100% 50%;
  }
}
.slide-in-left {
	-webkit-animation: slide-in-left 2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: slide-in-left 2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

@-webkit-keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}

.slide-in-top {
	-webkit-animation: slide-in-top 2s cubic-bezier(0.250, 0.460, 0.450, 0.940) 3s both;
	        animation: slide-in-top 2s cubic-bezier(0.250, 0.460, 0.450, 0.940) 3s both;
}
/* ----------------------------------------------
 * Generated by Animista on 2022-1-28 9:44:22
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-top
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-top {
  0% {
    -webkit-transform: translateY(-1000px);
            transform: translateY(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}
@keyframes slide-in-top {
  0% {
    -webkit-transform: translateY(-1000px);
            transform: translateY(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}

</style>